### ISSUE TITLE
Jam update-builder cli is removing optional flag from group order entries

### ISSUE THREAD

**Issue by petermylemans** [paketo-buildpacks/packit#122]
## What happened?
When running the jam CLI optional flags are removed from builder group order entries. Additionally empty version tags are introduced when the version was left to "inferred".

* What were you attempting to do?
Run `jam update-builder --builder-file builder.toml` to update a builder.toml file with the latest versions.

* What did you expect to happen?
Jam update should follow the https://buildpacks.io/docs/reference/config/builder-config/
 `version` is optional and is included in case of non-empty
 `optional` is optional and is included in case it was set to true. This data currently disappears.

* What was the actual behavior? Please provide log output, if possible.

**BEFORE**

```toml
description = "Ubuntu bionic base image with buildpacks for Java, .NET Core, NodeJS, Go, Ruby, NGINX and Procfile"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/ca-certificates:2.1.0"
  version = "2.1.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/spring-boot:4.0.0"
  version = "4.0.0"

[lifecycle]
  version = "0.10.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    
  [[order.group]]
    id = "paketo-buildpacks/spring-boot"
    version = "4.0.0"
    optional = true

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.0.22-base-cnb"
  id = "io.buildpacks.stacks.bionic"
  run-image = "index.docker.io/paketobuildpacks/run:base-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:base-cnb"]
```
**AFTER**

```toml
description = "Ubuntu bionic base image with buildpacks for Java, .NET Core, NodeJS, Go, Ruby, NGINX and Procfile"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/ca-certificates:2.1.0"
  version = "2.1.0"

[[buildpacks]]
  uri = "docker://gcr.io/paketo-buildpacks/spring-boot:4.0.0"
  version = "4.0.0"

[lifecycle]
  version = "0.10.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    version = ""
    
  [[order.group]]
    id = "paketo-buildpacks/spring-boot"
    version = "4.0.0"

[stack]
  build-image = "docker.io/paketobuildpacks/build:1.0.22-base-cnb"
  id = "io.buildpacks.stacks.bionic"
  run-image = "index.docker.io/paketobuildpacks/run:base-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:base-cnb"]
```

## Build Configuration
jam v0.7.0 on Linux x64
