### ISSUE TITLE
jam update-builder and update-buildpack fail to update buildpack versions if registry path != buildpack ID

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/packit#141]
jam [update-builder](https://github.com/paketo-buildpacks/packit/blob/dfcde189172c97d4dd4aa0dfff609a1bcf95b413/cargo/jam/commands/update_builder.go#L56) and [update-buildpack](https://github.com/paketo-buildpacks/packit/blob/dfcde189172c97d4dd4aa0dfff609a1bcf95b413/cargo/jam/commands/update_buildpack.go#L64) assume that the registry path for the buildpack (sans domain) will be the same as its ID.

For instance, in the Paketo Nodejs `buildpack.toml`:
registry path: `"gcr.io/paketo-buildpacks/node-engine:0.2.2"`
buildpack id: `paketo-buildpacks/node-engine`

However, it's easy for an image to violate that convention. For example, the *same* buildpack can also be pulled from registry path: `paketobuildpacks/node-engine`. 

The buildpack's ID is part of the OCI image's labels, and is still: `paketo-buildpacks/node-engine`.

This causes a bug where `jam update buildpack` fails to update the version of a buildpack in the `buildpack.toml`.

To reproduce:

1. Create a `buildpack.toml` and `package.toml` where image URI is in `paketobuildpacks` org on Dockerhub. Select an old version of the buildpack (0.2.2 is current latest)

`buildpack.toml`
```toml
api = "0.2"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "paketo-buildpacks/nodejs"
  name = "Paketo Node.js Buildpack"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.2.1"
```
`package.toml`
```toml
[buildpack]
  uri = "build/buildpack.tgz"

[[dependencies]]
  uri = "docker://paketobuildpacks/node-engine:0.2.1"
```

2. Run `jam update-buildpack --buildpack-file buildpack.toml --package-file package.toml`
3. See that the `package.toml` has been updated, but the `buildpack.toml` has not.
