### ISSUE TITLE
Implement Buildpack RFC 0064: Buildpacks contribute default process type

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/packit#150]
## Summary
Buildpack [RFC0064](https://github.com/buildpacks/rfcs/blob/main/text/0064-buildpacks-contribute-default-process-type.md) allows buildpacks to specify a default process type. This can be achieved by including a `default = true` flag when specifying the processes in the `launch.toml`.

```toml
[[processes]]
type = "web"
command = "bundle exec ruby app.rb"
default = true

[[processes]]
type = "worker"
command = "bundle exec ruby worker.rb"
```

In this case, the `web` process will be treated as the default when the built image is run.

## Proposal
We will need to add a new `Default` field on the `packit.Process` type. This field will default to `false` and should be omitted from the generated `launch.toml` when set to `false`.

For buildpacks that are using Buildpack API 0.6 or higher, include the `default` field, but only when marked `true`.

For buildpacks that are using a version of the Buildpack API less than 0.6, throw an error if any process is marked as default, explaining that this feature is only available in buildpacks using API v0.6 and higher.
