### ISSUE TITLE
Implement Buildpack RFC 0070: New Buildpack Descriptor Keys

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/packit#151]
## Summary
Buildpack [RFC0070](https://github.com/buildpacks/rfcs/blob/main/text/0070-new-buildpack-toml-keys.md) introduces some new fields into the `buildpack.toml` file. These fields include `description`, `keywords`, and `licenses`. The specific changes to the `buildpack.toml` would look like the following:

```toml
[buildpack]
description = "<buildpack description>"
keywords = [ "<string>" ]

[[buildpack.licenses]]
type = "<string>"
uri = "<uri>"
```

To support this, we will need to make changes to both `jam` and the top-level `packit` API.

## Proposal

1. When we `jam pack` a buildpack that includes these new keys, and is specifying buildpack API >= 0.6, include these keys in the built buildpack artifact.

2. Include these fields in the `packit.BuildpackInfo` type so that they can be accessed by the buildpack itself at runtime should they need to.
