### ISSUE TITLE
Service Binding - "dependency-mapping" will not work on Kubernetes - colon not allowed in Secret key name

### ISSUE THREAD

**Issue by ChuckQuinnIV** [paketo-buildpacks/packit#521]
Similar to https://github.com/paketo-buildpacks/packit/issues/453, sha256:b4cb31162ff6d7926dd09e21551fa745fa3ae1758c25148b48dadcf78ab0c24c as a key name cannot work on Kubernetes as ':' is not allowed as a key in a Kubernetes secret
```
$SERVICE_BINDING_ROOT
└── my-dependency-binding
    ├── type -> "dependency-mapping"
    ├── sha256:b4cb31162ff6d7926dd09e21551fa745fa3ae1758c25148b48dadcf78ab0c24c -> https://example.com/dep-1.tgz
    └── sha256:efa6d87993ff21615e2d8fc0c98e07ff357fc9f3b9bd93c2cf58ba7f2b6fd2e0 -> https://example.com/dep-2.tgz
```

link to [dependency-mapping](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0010-dependency-mappings.md#service-binding-specification-for-kubernetes-example) documentation

Motivation here is to build dotnet applications offline, which uses sha512 in their manifests.

**Comment by sophiewigmore** [comment]
Hey @ChuckQuinnIV, it's interesting that we've never run into that on Kubernetes before. What's the error that you get back when you try to use the `:`?

**Comment by ChuckQuinnIV** [comment]
Sure! I could absolutely be doing something wrong here, but following our current format for defining dependency-mappings in a Kubernetes Secret (like so):

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: dependency-mapping
type: service.binding/dependency-mapping
stringData:
  type: dependency-mapping
  ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad: https://my-internal-url-foo.example.com/dependency1.zip # works fine
  sha512:ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f: https://my-internal-url-foo.example.com/dependency2.zip # breaks
```

Attempting to submit that key with `sha512:`, following [RFC 10](https://github.com/paketo-buildpacks/rfcs/blob/main/text/0010-dependency-mappings.md), results in this error from Kubernetes:
`a valid config key must consist of alphanumeric characters, '-', '' or '.' (e.g. 'key.name', or 'KEY_NAME', or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')`
